document non-revenue trips
mbta/gtfs-documentation pull request #42
Opened 2023-10-23 20:15 UTC by Whoops

Asana Task: [[extra] 📝🚝🚫💰 Update GTFS-RT Documentation to explain non-revenue service representation](https://app.asana.com/0/584764604969369/1205761861495467/f)

2023-10-24 12:37 UTC, rymarczy commented
How is this `uncertainty` value different and/or the same compared to the `uncertainty` values specified in the `StopTimeEvent` message? https://gtfs.org/realtime/reference/#message-stoptimeevent

2023-10-24 14:34 UTC, Whoops commented
> How is this `uncertainty` value different and/or the same compared to the `uncertainty` values specified in the `StopTimeEvent` message? https://gtfs.org/realtime/reference/#message-stoptimeevent

Whoops, it isn't. I had it on the wrong message. I've updated the PR to fix that!

2023-10-24 16:30 UTC, Whoops commented on reference/gtfs-realtime.md
> +[mtse]: https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/reference.md#message-stoptimeevent
Thanks!

2023-10-24 19:50 UTC, fsaid90 commented on reference/gtfs-realtime.md
> +300 | Real-time prediction not available. This code is primarily used when a vehicle has not yet been assigned to the trip, (i.e. because the block has not started yet). It is a schedule-based predic
I don't know that we should mention Swiftly by name here - I'd prefer that we reword to remove references to Swiftly specifically, but tagging @jfabi to get his view as well

2023-10-24 19:51 UTC, fsaid90 commented on reference/gtfs-realtime.md
> +For Rail trips:
Do we have uncertainty values for CR predictions?

If we do, we might have to stratify this further (and we'd have to look for Swiftly's definitions)

2023-10-24 19:53 UTC, fsaid90 commented on reference/gtfs-realtime.md
> +within the yard may be exposed in the enchanced feed as non-revenue trips. In general,
Suggest rewording "such as travelling to the start of a trip, or movements within the yard may be exposed" to "such as traveling to the start point of a trip or movements within a yard,"

2023-10-24 19:54 UTC, fsaid90 commented on reference/gtfs-realtime.md
> +Non-revenue trips will only appear in the enhanced feed.
Suggest removing "will"

2023-10-24 19:56 UTC, fsaid90 commented on reference/gtfs-realtime.md
> +these trips may appear as revenue trips in the feeds.
Suggested rewording of 

"At this time we are working to identify non-revenue light rail trips. In the meantime
these trips may appear as revenue trips in the feeds."

to

"At this time, we are continuing to work on identifying non-revenue light rail trips (Green Line, Mattapan Trolley). In the meantime, these trips may appear as revenue trips in the feeds."

2023-10-25 20:30 UTC, Whoops commented on reference/gtfs-realtime.md
> +within the yard may be exposed in the enchanced feed as non-revenue trips. In general,
done.

2023-10-25 20:31 UTC, Whoops commented on reference/gtfs-realtime.md
> +300 | Real-time prediction not available. This code is primarily used when a vehicle has not yet been assigned to the trip, (i.e. because the block has not started yet). It is a schedule-based predic
Agreed. I've rephrased to we.

2023-10-25 20:31 UTC, Whoops commented on reference/gtfs-realtime.md
> +Non-revenue trips will only appear in the enhanced feed.
done.

2023-10-25 20:31 UTC, Whoops commented on reference/gtfs-realtime.md
> +these trips may appear as revenue trips in the feeds.
Good idea! Added

2023-12-11 20:26 UTC, meagharty commented on reference/gtfs-realtime.md
> +may be exposed in the enchanced feed as non-revenue trips. In general, these trips should not be shown
typo: enhanced

2023-12-11 20:26 UTC, meagharty commented on reference/gtfs-realtime.md
> +to riders as they do not accept passengers. These trips can be identified `trip_id`within the
nit: can we add a space after `trip_id`?

2023-12-11 20:26 UTC, meagharty commented on reference/gtfs-realtime.md
> +- [Standard](#standard-feeds)
It looks like there's some accidental duplication with these links

2023-12-11 20:26 UTC, meagharty commented on reference/gtfs-realtime.md
> +| message                                      | object                                            |
ty for the fixed spacing in the text rendering 😌 👍

2023-12-22 16:04 UTC, fsaid90 requested changes

2023-12-22 16:04 UTC, fsaid90 commented on reference/gtfs-realtime.md
> +to riders as they do not accept passengers. These trips can be identified `trip_id` within the
We should probably update this to reflect the actual identification mechanism per the revised revenue TripDescriptor

2023-12-22 17:58 UTC, fsaid90 approved these changes
LGTM! Thank you 😃

2023-12-22 17:59 UTC, merged